### PR TITLE
Use of let and const over var

### PR DESCRIPTION
**Pull request by austinstarin**

### CODE REVIEW

**Review by bgantick — APPROVED** [review]
🔥

**Comment by abea** [comment]
This is legacy project terrorism.

**Comment by bgantick** [comment]
I think this should be a thing for new projects. Perhaps use `.eslintignore` for legacy projects?

**Review by boutell — APPROVED** [review]

**Comment by boutell** [comment]
@abea, If I recall properly, a project can have its own eslint config that shuts off some stuff, right? 

See:

https://github.com/apostrophecms/apostrophe/blob/master/.eslintrc

For how the apostrophe module inherits from punkave but then shuts some stuff off.

I suppose we will have to add a new rule to apostrophe's conf to shut this new thing off, but I'm OK with that. 

(Apostrophe is sufficiently independent of our in-house new-project standards that it's possible I should copy in the punkave config and just let them fork, and revisit for 3.x. You could do the same to provide a stable base for 0.5 and 2.x legacy projects.)

**Comment by boutell** [comment]
Hmmm. However... I would be sympathetic to the proposal that "punkave" should become a legacy spec and "punkave2018" should come into being for new projects. That seems to me more logical than creating a lot of busywork for the support team and myself because we want to make a backwards incompatible change to the rules.

**Review by boutell — CHANGES_REQUESTED** [review]
I have come around to the point of view that this is too big a change to a standard that is included by reference into legacy projects and apostrophe. We should create a 2018 standard for new projects to inherit.

**Review by boutell — APPROVED** [review]
I spoke with @abea who has explained that he's fine with pinning projects as they go along to an older version of the punkave spec. That does make sense, so I'm withdrawing my earlier objection. For Apostrophe I'm going to create a separate spec, because I need stability in things like travis badges.

**Comment by boutell** [comment]
These are npm packages. Why not use a new major version number? I bet the dependencies in our legacy projects are already set up with semver ranges that will automatically keep them to the previous one.

**Comment by bgantick** [comment]
Good call @boutell - I'll go ahead and merge this

**Comment by austinstarin** [comment]
Can we wait for everyone to check off their review before merging the next time around? I'm just getting to this thread.

**Comment by bgantick** [comment]
Apologies - I thought we were going with two approvals for merging.

**Pull request merged**
